### ISSUE TITLE
Degit error with default branch "master"

### ISSUE THREAD

**Issue by fnzip** [antfu/vitesse-lite#1]
Hi, so i want use this template and install with degit but i got error thats say

```
! could not find commit hash for master
```

I think thats error because this repo use branch `main` instead of `master`, so i add param `#main` to template name on degit and its working.

And please read my PR [#14](https://github.com/antfu/vitesse-webext/pull/14) to fix it

**Comment by fnzip** [comment]
Oh, sorry have wrong tagging repository, but both have same error

[#2](https://github.com/antfu/vitesse-lite/pull/2)

**Comment by fnzip** [comment]
FIX https://github.com/antfu/vitesse-webext/pull/14#issuecomment-900065888

**Comment by amasoudnia** [comment]
It might be because the default branch on the targeted repository provider is changed so:
1- First clear the npm cache by: npm cache clean --force
2- Upgrade digit to the latest version: npm install -g degit@latest

If none of the above helps check if your git is the latest version or check if you have missed placing it in the environment variable "path",
